### ISSUE TITLE
Used a double instead of a BigDecimal for commission

### ISSUE THREAD

**Issue by SamMeek** [SamMeek/PerformanceCentre#1]

**Comment by cookierebel** [comment]
This is fixed, right?

**Comment by SamMeek** [comment]
No, I ran out of time last night to do it but I thought I'd log the issue
to let you know that I'm aware of my mistake.

**Comment by SamMeek** [comment]
Fixed in the commit: https://github.com/SamMeek/PerformanceCentre/commit/968170aa63c7e305ee806f7675be7a0cc2c856bb 

Not very happy with how complex this made the commission calculation look but I can't see a way around that without sacrificing accuracy. In the real world I'd need to performance test my implementation.
