### ISSUE TITLE
Use double instead of ints for Target and Actual

### ISSUE THREAD

**Issue by cookierebel** [SamMeek/PerformanceCentre#2]
Targets and actuals can either be number of items sold, in which case they would be integers - but they can also be $ sold, in which case they would be decimals. Currently the application does not support that.

**Comment by SamMeek** [comment]
I'll clean this up. I'd made the assumption that it was always units sold.

**Comment by SamMeek** [comment]
Fixed via commit: https://github.com/SamMeek/PerformanceCentre/commit/abf9afeb7490629449e0d7e708fcc65a25bc0b1e
